### PR TITLE
67 year animation

### PR DESCRIPTION
**Pull request by ClConr**
Animation works, Inductees have uneven spacing on sides while EE do not despite same component

### CODE REVIEW

**Comment by ClConr** [comment]
I also found another issue where isotope only works for one of the InducteeNavs and it is causing the spacing issue

**Comment by ethangambles** [comment]
@ClConr I added a small change that should hopefully fix the padding. I like it overall, can we slow down the animation at all? It goes pretty quick.

**Comment by ethangambles** [comment]
@ClConr Also, not sure if this is because of your changes, but the 2020 year does not work correctly anymore

**Comment by ethangambles** [comment]
> > @ClConr I added a small change that should hopefully fix the padding. I like it overall, can we slow down the animation at all? It goes pretty quick.
> 
> Also, it might be possible through some CSS but the transition is from the isotope filter so not sure if we can change it.

Ok. I'll look into that a bit. Can you also add it to the years of the founders series page?

**Comment by ethangambles** [comment]
@ClConr I fixed the transition speed and the 2020 exception. Once we get it on the founders series page, it'll be ready to merge.

**Pull request merged**
